id = "groovy"
name = "Groovy"
version = "0.1.0"
schema_version = 1

description = "Groovy DSL support."
repository = "https://github.com/valentinegb/zed-groovy"
authors = ["Valentine Briese <valentinegb@icloud.com>"]

# [language_servers.groovy]
# name = "Groovy"
# language = "Groovy"

[grammars.groovy]
repository = "https://github.com/Decodetalkers/tree-sitter-groovy"
rev = "7e023227f46fee428b16a0288eeb0f65ee2523ec"
