id = "groovy"
name = "Groovy"
version = "1.3.0"
schema_version = 1
authors = ["Valentine Briese <valentinegb@icloud.com>"]
description = "Groovy (build.gradle) support."
repository = "https://github.com/valentinegb/zed-groovy"

[language_servers.groovy]
name = "Groovy"
language = "Groovy"

[grammars.groovy]
repository = "https://github.com/murtaza64/tree-sitter-groovy"
rev = "86911590a8e46d71301c66468e5620d9faa5b6af"
